#!/usr/bin/env python3
"""Convert umeo test-scenario HTML files into Zensical Markdown pages.

Each TS-* folder contains one self-contained HTML file (images embedded as
base64) plus an images/ folder with the same screenshots as real PNGs.
Figures appear in the HTML in the same order as the numerically-prefixed
files in images/, so figure N maps to sorted(images)[N].

Output: <dest>/<TS-folder-name>/index.md + images/ copied alongside.
"""
import html
import re
import shutil
import sys
from html.parser import HTMLParser
from pathlib import Path

SRC = Path("/Users/yavuzoncu/Desktop/umeo/test-scenarios")
# English tree only — nb/sv translations under docs/nb and docs/sv are
# maintained by hand and NOT regenerated by this script.
DEST = Path("/Users/yavuzoncu/Documents/zensical-sp/docs/en/scenarios")

# Display order and titles (all languages). Folder slugs / tracking ids stay
# stable so URLs and collected DynamoDB data never break; only what users SEE
# is renumbered. The source HTML h1 is ignored in favor of these titles.
DISPLAY = {
    "TS-04-studies-and-programs": (1, {
        "en": "Test Scenario 01 — Settings - Studies & Programs",
        "nb": "Testscenario 01 — Innstillinger - Studier og programmer",
        "sv": "Testscenario 01 — Inställningar - Studier och program"}),
    "TS-05-study-admins": (2, {
        "en": "Test Scenario 02 — Settings - Study Admins",
        "nb": "Testscenario 02 — Innstillinger - Studieadministratorer",
        "sv": "Testscenario 02 — Inställningar - Studieadministratörer"}),
    "TS-06-dashboard-items": (3, {
        "en": "Test Scenario 03 — Settings - Dashboard Items",
        "nb": "Testscenario 03 — Innstillinger - Dashbordelementer",
        "sv": "Testscenario 03 — Inställningar - Dashboardelement"}),
    "TS-07-connect-praksis-place": (4, {
        "en": "Test Scenario 04 — Connect a Praksis Place to UH",
        "nb": "Testscenario 04 — Koble et praksissted til UH",
        "sv": "Testscenario 04 — Anslut en praktikplats till UH"}),
    "TS-08-explore-praksis-place": (5, {
        "en": "Test Scenario 05 — Explore a Praksis Place",
        "nb": "Testscenario 05 — Utforsk et praksissted",
        "sv": "Testscenario 05 — Utforska en praktikplats"}),
    "TS-01-create-quota-request": (6, {
        "en": "Test Scenario 06 — Quota Request - Create",
        "nb": "Testscenario 06 — Kvoteforespørsel - Opprett",
        "sv": "Testscenario 06 — Kvotförfrågan - Skapa"}),
    "TS-02-approve-quota-request": (7, {
        "en": "Test Scenario 07 — Quota Request - Approve as PK",
        "nb": "Testscenario 07 — Kvoteforespørsel - Godkjenn som PK",
        "sv": "Testscenario 07 — Kvotförfrågan - Godkänn som PK"}),
    "TS-03-search-and-filters": (8, {
        "en": "Test Scenario 08 — Quota Request - Search & Filters",
        "nb": "Testscenario 08 — Kvoteforespørsel - Søk og filtre",
        "sv": "Testscenario 08 — Kvotförfrågan - Sök och filter"}),
    "TS-09-create-placement": (9, {
        "en": "Test Scenario 09 — Student Placement - Create",
        "nb": "Testscenario 09 — Studentplassering - Opprett",
        "sv": "Testscenario 09 — Studentplacering - Skapa"}),
}

# Renumbered cross-references inside the English prose (old number -> new).
# Applied to the generated EN markdown; nb/sv carry the same fixes by hand.
# Order matters: 01->06 must run before 04->01 so the result of the latter
# is not rewritten again.
EN_XREFS = [
    ("requires Test Scenario 01.", "requires Test Scenario 06."),
    ("*Test Scenario 01*", "*Test Scenario 06*"),
    ("*Test Scenario 04*", "*Test Scenario 01*"),
]


class MdConverter(HTMLParser):
    def __init__(self, image_files):
        super().__init__(convert_charrefs=True)
        self.image_files = image_files
        self.fig_index = 0
        self.out = []          # list of markdown blocks
        self.buf = []          # inline text buffer for current block
        self.block = None      # current block type
        self.list_counter = None
        self.in_figcaption = False
        self.caption = []
        self.meta = {}         # Page/Role/Goal/Precondition
        self.title = None
        self.pending_meta_key = None
        self.step_no = None
        self.in_step_span = False
        self.in_raw = None     # inside script/style/title

    # -- helpers ---------------------------------------------------------
    def flush_inline(self):
        text = "".join(self.buf)
        text = re.sub(r"[ \t]+", " ", text)
        self.buf = []
        return text.strip()

    # -- parser hooks ----------------------------------------------------
    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        cls = attrs.get("class", "")
        if self.in_raw:
            return
        if tag in ("script", "style", "title"):
            self.in_raw = tag
            return
        if tag in ("h1", "h2", "h3", "p"):
            self.block = tag
            self.buf = []
            self.is_meta = tag == "p" and "meta" in cls
        elif tag == "ol":
            self.list_counter = int(attrs.get("start", 1))
            self.out.append(("ol-start", None))
        elif tag == "ul":
            self.list_counter = "-"
            self.out.append(("ol-start", None))
        elif tag == "li":
            self.buf = []
        elif tag == "table":
            self.table_rows = []
        elif tag == "tr":
            self.table_row = []
        elif tag in ("th", "td"):
            self.buf = []
        elif tag == "figure":
            self.caption = []
        elif tag == "figcaption":
            self.in_figcaption = True
            self.buf = []
        elif tag == "img":
            self.current_img = attrs.get("alt", "")
        elif tag == "span" and "step" in cls and self.block == "h3":
            self.in_step_span = True
        elif tag == "b" or tag == "strong":
            self.buf.append("**")
        elif tag == "i" or tag == "em":
            self.buf.append("*")
        elif tag == "code":
            self.buf.append("`")
        elif tag == "hr":
            self.out.append(("hr", None))
        elif tag == "br":
            self.buf.append(" ")

    def handle_endtag(self, tag):
        if self.in_raw:
            if tag == self.in_raw:
                self.in_raw = None
            return
        if tag == "h1":
            self.title = self.flush_inline().replace("**", "").replace("*", "")
            self.block = None
        elif tag in ("h2", "h3"):
            text = self.flush_inline()
            if tag == "h3" and self.step_no is not None:
                text = f"{text}"
            level = "##" if tag == "h2" else "###"
            prefix = f"{self.step_no}. " if (tag == "h3" and self.step_no) else ""
            self.out.append(("heading", f"{level} {prefix}{text}"))
            self.step_no = None
            self.block = None
        elif tag == "p":
            text = self.flush_inline()
            if not text:
                pass
            elif self.is_meta:
                # split "**Key:** value" pairs, possibly multiple per line
                parts = re.split(r"•", text)
                for part in parts:
                    m = re.match(r"\s*\*\*(.+?):\*\*\s*(.*)", part.strip())
                    if m:
                        self.meta[m.group(1)] = m.group(2).strip()
            else:
                self.out.append(("p", text))
            self.block = None
            self.is_meta = False
        elif tag == "li":
            text = self.flush_inline()
            if self.list_counter == "-":
                self.out.append(("li", f"-   {text}"))
            else:
                self.out.append(("li", f"{self.list_counter}.  {text}"))
                self.list_counter += 1
        elif tag in ("th", "td"):
            self.table_row.append(self.flush_inline())
        elif tag == "tr":
            if self.table_row:
                self.table_rows.append(self.table_row)
        elif tag == "table":
            if self.table_rows:
                self.out.append(("table", self.table_rows))
        elif tag == "figcaption":
            self.in_figcaption = False
            self.caption = self.flush_inline()
        elif tag == "figure":
            alt = getattr(self, "current_img", "") or ""
            self.out.append(("figure", (alt, self.caption or alt)))
            self.current_img = None
        elif tag == "span" and self.in_step_span:
            self.in_step_span = False
        elif tag in ("b", "strong"):
            self.buf.append("**")
        elif tag in ("i", "em"):
            self.buf.append("*")
        elif tag == "code":
            self.buf.append("`")

    def handle_data(self, data):
        if self.in_raw:
            return
        if self.in_step_span:
            num = data.strip()
            if num.isdigit():
                self.step_no = num
            return
        self.buf.append(data)


def tokens(s):
    return set(re.findall(r"[a-z]+", s.lower())) - {"the", "a", "an", "of", "and", "page", "state"}


def assign_images(figures, image_files):
    """Map each (alt, caption) figure to an image file.

    Sequential when counts match; otherwise greedy best-token-overlap
    against remaining files, preserving file order.
    """
    if len(figures) == len(image_files):
        return list(image_files)
    result, remaining = [], list(image_files)
    for alt, caption in figures:
        fig_tok = tokens(alt) | tokens(caption)
        best, best_score = None, -1.0
        for i, fname in enumerate(remaining):
            score = len(fig_tok & tokens(fname)) - i * 0.01
            if score > best_score:
                best, best_score = i, score
        result.append(remaining.pop(best))
        # keep order monotonic: drop files that sort before the chosen one
        remaining = [f for f in remaining if f > result[-1]]
    return result


def render(conv: MdConverter, slug: str) -> str:
    figures = [v for k, v in conv.out if k == "figure"]
    image_files = [f for f in conv.image_files]
    assigned = assign_images(figures, image_files)
    fig_i = 0
    lines = ["---", f"title: {conv.title}", "---", "", f"# {conv.title}", ""]
    if conv.meta:
        lines.append('!!! info "Scenario overview"')
        lines.append("")
        for k, v in conv.meta.items():
            lines.append(f"    - **{k}:** {v}")
        lines.append("")
    prev = None
    for kind, val in conv.out:
        if kind == "heading":
            lines += [val, ""]
        elif kind == "p":
            lines += [val, ""]
        elif kind == "ol-start":
            pass
        elif kind == "li":
            lines.append(val)
            prev = "li"
            continue
        elif kind == "hr":
            lines += ["---", ""]
        elif kind == "table":
            header, *body = val
            lines.append("| " + " | ".join(header) + " |")
            lines.append("|" + "---|" * len(header))
            for row in body:
                lines.append("| " + " | ".join(row) + " |")
            lines.append("")
        elif kind == "figure":
            alt, caption = val
            fname = assigned[fig_i]
            fig_i += 1
            lines += [
                '<figure markdown="span">',
                f"  ![{alt}](images/{fname})",
                f"  <figcaption>{caption}</figcaption>",
                "</figure>",
                "",
            ]
        if prev == "li":
            lines.insert(-1, "") if False else None
        prev = kind
    # ensure blank line after list blocks
    text = "\n".join(lines)
    text = re.sub(r"(\n(?:\d+\.  |-   )[^\n]*)\n(?=[^\d\-\n])", r"\1\n\n", text)
    text = text.rstrip() + "\n"
    # feedback widget anchor, populated by javascripts/app.js
    text += (
        "\n---\n\n"
        f'<div class="hc-feedback" data-scenario="{slug}"></div>\n'
    )
    return text


def main():
    DEST.mkdir(parents=True, exist_ok=True)
    folders = sorted(p for p in SRC.iterdir() if p.is_dir() and p.name.startswith("TS-"))
    manifest = []
    for folder in folders:
        html_files = list(folder.glob("*.html"))
        if len(html_files) != 1:
            print(f"SKIP {folder.name}: {len(html_files)} html files")
            continue
        images_dir = folder / "images"
        image_files = sorted(f.name for f in images_dir.glob("*.png")) if images_dir.exists() else []
        raw = html_files[0].read_text(encoding="utf-8", errors="ignore")
        conv = MdConverter(image_files)
        conv.feed(raw)
        n_figs = sum(1 for k, _ in conv.out if k == "figure")
        status = "OK" if n_figs == len(image_files) else f"FUZZY figs={n_figs} imgs={len(image_files)}"
        print(f"{folder.name}: {status}, title={conv.title!r}, meta keys={list(conv.meta)}")
        out_dir = DEST / folder.name
        out_dir.mkdir(parents=True, exist_ok=True)
        md = render(conv, folder.name)
        disp = DISPLAY.get(folder.name)
        if disp:
            md = md.replace(f"title: {conv.title}", f"title: {disp[1]['en']}", 1)
            md = md.replace(f"# {conv.title}", f"# {disp[1]['en']}", 1)
        for old, new in EN_XREFS:
            md = md.replace(old, new)
        (out_dir / "index.md").write_text(md, encoding="utf-8")
        if status.startswith("FUZZY"):
            for line in md.splitlines():
                if "](images/" in line:
                    print("   ", line.strip())
        if images_dir.exists():
            dest_img = out_dir / "images"
            if dest_img.exists():
                shutil.rmtree(dest_img)
            shutil.copytree(images_dir, dest_img)
        manifest.append((folder.name, conv.title))
    print("\nNAV entries:")
    for slug, title in manifest:
        print(f'  {{ "{title}" = "scenarios/{slug}/index.md" }},')
    # scenario manifest consumed by app.js (progress/admin pages), in the
    # DISPLAY order/titles below (see module docstring: slugs stay stable).
    js_dir = DEST.parent.parent / "javascripts"
    js_dir.mkdir(parents=True, exist_ok=True)
    slugs = {slug for slug, _ in manifest}
    blocks = []
    for slug, (order, titles) in sorted(DISPLAY.items(), key=lambda kv: kv[1][0]):
        if slug not in slugs:
            continue
        blocks.append(
            "  {\n"
            f'    id: "{slug}",\n'
            "    title: {\n"
            f'      en: "{titles["en"]}",\n'
            f'      nb: "{titles["nb"]}",\n'
            f'      sv: "{titles["sv"]}",\n'
            "    },\n"
            "  },"
        )
    (js_dir / "scenarios.js").write_text(
        "// Scenario manifest in DISPLAY ORDER with titles per language (en/nb/sv).\n"
        "// Folder slugs / tracking ids are stable and intentionally do NOT match\n"
        "// the display numbering. Maintained together with tools/convert_scenarios.py.\n"
        "export const SCENARIOS = [\n" + "\n".join(blocks) + "\n];\n",
        encoding="utf-8",
    )
    print(f"\nWrote {js_dir / 'scenarios.js'}")


if __name__ == "__main__":
    main()
